// Sample data array
var items = [
    { id: 1, name: "Appliances: barbeque" },
    { id: 2, name: "Appliances: cooktop" },
    { id: 3, name: "Appliances: dishwasher" },
    { id: 4, name: "Appliances: dryer" },
    { id: 5, name: "Appliances: microwave" },
    { id: 6, name: "Appliances: oven" },
    { id: 7, name: "Appliances: range" },
    { id: 8, name: "Appliances: refrigerator" },
    { id: 9, name: "Appliances: refrigerator - undercounter" },
    { id: 10, name: "Appliances: vacuum" },
    { id: 11, name: "Appliances: washing machine" },
    { id: 12, name: "Asphalt: asphalt" },
    { id: 13, name: "Audio Visual Equipment: boom boxes" },
    { id: 14, name: "Audio Visual Equipment: projection screens" },
    { id: 15, name: "Audio Visual Equipment: speakers" },
    { id: 16, name: "Bath Accessories: glass shelf" },
    { id: 17, name: "Bath Accessories: grab bars" },
    { id: 18, name: "Bath Accessories: medicine cabinet" },
    { id: 19, name: "Bath Accessories: paper towel dispenser" },
    { id: 20, name: "Bath Accessories: rob hooks" },
    { id: 21, name: "Bath Accessories: shower caddie" },
    { id: 22, name: "Bath Accessories: shower rod/curtain" },
    { id: 23, name: "Bath Accessories: soap dispenser" },
    { id: 24, name: "Bath Accessories: toilet paper dispenser" },
    { id: 25, name: "Bath Accessories: toilet paper holder" },
    { id: 26, name: "Bath Accessories: towel bar" },
    { id: 27, name: "Bath Accessories: towel ring" },
    { id: 28, name: "Cabinetry and Casework: cabinets - painted" },
    { id: 29, name: "Cabinetry and Casework: cabinets - stain grade" },
    { id: 30, name: "Concrete: car bumpers" },
    { id: 31, name: "Concrete: curbs and gutters" },
    { id: 32, name: "Concrete: flatwork" },
    { id: 33, name: "Concrete: grade beams" },
    { id: 34, name: "Concrete: piers" },
    { id: 35, name: "Concrete: structural columns" },
    { id: 36, name: "Concrete: structural floor decks" },
    { id: 37, name: "Concrete: structural slabs" },
    { id: 38, name: "Concrete: structural walls" },
    {
        id: 39,
        name: "Conveyance equipment: automated vehicle storage and retrieval systems",
    },
    { id: 40, name: "Conveyance equipment: dumbwaiters" },
    { id: 41, name: "Conveyance equipment: elevators" },
    { id: 42, name: "Conveyance equipment: escalators" },
    { id: 43, name: "Conveyance equipment: lift systems for accessibility" },
    { id: 44, name: "Conveyance equipment: moving walks" },
    { id: 45, name: "Conveyance equipment: pneumatic tube systems" },
    { id: 46, name: "Countertops: engineered stone" },
    { id: 47, name: "Countertops: natural stone" },
    { id: 48, name: "Countertops: plastic laminate" },
    { id: 49, name: "Doors: doors no glass" },
    { id: 50, name: "Doors: doors with glass" },
    { id: 51, name: "Doors: garage door opener" },
    { id: 52, name: "Doors: garage doors" },
    { id: 53, name: "Doors: screen doors" },
    { id: 54, name: "Drywall: drywall" },
    { id: 55, name: "Electrical: 2x4 compact florescent lghts" },
    { id: 56, name: "Electrical: breaker boxes" },
    { id: 57, name: "Electrical: ceiling fans" },
    { id: 58, name: "Electrical: decorative lights" },
    { id: 59, name: "Electrical: disconnects" },
    { id: 60, name: "Electrical: emergency lights" },
    { id: 61, name: "Electrical: exit signs" },
    { id: 62, name: "Electrical: main panel" },
    { id: 63, name: "Electrical: recessed can lights" },
    { id: 64, name: "Electrical: subpanel" },
    { id: 65, name: "Electrical: switchgear" },
    { id: 66, name: "Electrical: track lighting" },
    { id: 67, name: "Electrical: light fixtures - exterior" },
    { id: 68, name: "Firesprinklers:" },
    { id: 69, name: "Flooring: carpet" },
    { id: 70, name: "Flooring: carpet tiles" },
    { id: 71, name: "Flooring: cork" },
    { id: 72, name: "Flooring: hardwood" },
    { id: 73, name: "Flooring: lvp" },
    { id: 74, name: "Flooring: resilient" },
    { id: 75, name: "Flooring: rubber" },
    { id: 76, name: "Flooring: vct" },
    { id: 77, name: "Furniture/Furnishings: bar stools" },
    { id: 78, name: "Furniture/Furnishings: bean bag seats" },
    { id: 79, name: "Furniture/Furnishings: bed - frame" },
    { id: 80, name: "Furniture/Furnishings: bed - mattress" },
    { id: 81, name: "Furniture/Furnishings: chairs" },
    { id: 82, name: "Furniture/Furnishings: chaise lounge" },
    { id: 83, name: "Furniture/Furnishings: church pews" },
    { id: 84, name: "Furniture/Furnishings: couches" },
    { id: 85, name: "Furniture/Furnishings: curtains for dividers" },
    { id: 86, name: "Furniture/Furnishings: curtains for windows" },
    { id: 87, name: "Furniture/Furnishings: cushions" },
    { id: 88, name: "Furniture/Furnishings: desk" },
    { id: 89, name: "Furniture/Furnishings: dishware" },
    { id: 90, name: "Furniture/Furnishings: drying racks" },
    { id: 91, name: "Furniture/Furnishings: fireplace accessories" },
    { id: 92, name: "Furniture/Furnishings: folding chairs" },
    { id: 93, name: "Furniture/Furnishings: folding tables" },
    { id: 94, name: "Furniture/Furnishings: glassware" },
    { id: 95, name: "Furniture/Furnishings: mirrors - framed" },
    { id: 96, name: "Furniture/Furnishings: organizer trays" },
    { id: 97, name: "Furniture/Furnishings: pillows" },
    { id: 98, name: "Furniture/Furnishings: portable stages" },
    { id: 99, name: "Furniture/Furnishings: rugs" },
    { id: 100, name: "Furniture/Furnishings: storage tubs - plastic" },
    { id: 101, name: "Furniture/Furnishings: table lamps" },
    { id: 102, name: "Furniture/Furnishings: tables" },
    { id: 103, name: "Furniture/Furnishings: trash can" },
    { id: 104, name: "Furniture/Furnishings: tv" },
    { id: 105, name: "Furniture/Furnishings: utensiles" },
    { id: 106, name: "Furniture/Furnishings: wind chime" },
    { id: 107, name: "Glass and glazing: curtain wall" },
    { id: 108, name: "Glass and glazing: fixed glass" },
    { id: 109, name: "Glass and glazing: glass block" },
    { id: 110, name: "Glass and glazing: shower enclosure" },
    { id: 111, name: "Glass and glazing: stained glass" },
    { id: 112, name: "Glass and glazing: tub enclosure" },
    { id: 113, name: "Granite/Marble/etc. Slabs:" },
    { id: 114, name: "Gutters/Downspouts: downspouts" },
    { id: 115, name: "Gutters/Downspouts: gutters" },
    { id: 116, name: "Gutters/Downspouts: lambs tongues" },
    { id: 117, name: "Hardware: cabinet knobs and pulls" },
    { id: 118, name: "Hardware: deadbolt" },
    { id: 119, name: "Hardware: door closer" },
    { id: 120, name: "Hardware: door knob" },
    { id: 121, name: "Hardware: door lever" },
    { id: 122, name: "Hardware: door pulls" },
    { id: 123, name: "Hardware: entry lockset" },
    { id: 124, name: "Hardware: panic hardware" },
    { id: 125, name: "Hardware: security lock with keypad" },
    { id: 126, name: "Insulation: fiberglass batt" },
    { id: 127, name: "Insulation: mineral wool" },
    { id: 128, name: "Insulation: ply iso" },
    { id: 129, name: "Landscaping: benderboard" },
    { id: 130, name: "Landscaping: brick pavers" },
    { id: 131, name: "Landscaping: fire pit" },
    { id: 132, name: "Landscaping: grass" },
    { id: 133, name: "Landscaping: irrigation controller" },
    { id: 134, name: "Landscaping: potted plants" },
    { id: 135, name: "Landscaping: railroad ties" },
    { id: 136, name: "Landscaping: splashblocks" },
    { id: 137, name: "Landscaping: stone pavers" },
    { id: 138, name: "Landscaping: stones - large and loose" },
    { id: 139, name: "Landscaping: stones - medium and loose" },
    { id: 140, name: "Landscaping: stones - small and loose" },
    { id: 141, name: "Landscaping: turfblock" },
    { id: 142, name: "Lumber: beams" },
    { id: 143, name: "Lumber: cross laminated timbers" },
    { id: 144, name: "Lumber: columns" },
    { id: 145, name: "Lumber: dimensional" },
    { id: 146, name: "Lumber: glu lams" },
    { id: 147, name: "Lumber: laminated veneer lumber" },
    { id: 148, name: "Lumber: trusses" },
    { id: 149, name: "Lumber: composite decking" },
    { id: 150, name: "Masonry: artificial stone" },
    { id: 151, name: "Masonry: brick" },
    { id: 152, name: "Masonry: concrete block" },
    { id: 153, name: "Masonry: stone - natural - cut" },
    { id: 154, name: "Masonry: stone - natural - random" },
    { id: 155, name: "Masonry: stone - slabs" },
    { id: 156, name: "Mechanical: air filtration system" },
    { id: 157, name: "Mechanical: air handler" },
    { id: 158, name: "Mechanical: bath fan" },
    { id: 159, name: "Mechanical: cassettes - wall" },
    { id: 160, name: "Mechanical: chiller" },
    { id: 161, name: "Mechanical: condensers" },
    { id: 162, name: "Mechanical: decorative wall vents/registers" },
    { id: 163, name: "Mechanical: ductwork" },
    { id: 164, name: "Mechanical: floor vent registers" },
    { id: 165, name: "Mechanical: furnace" },
    { id: 166, name: "Mechanical: humidifier" },
    { id: 167, name: "Mechanical: return air grills" },
    { id: 168, name: "Mechanical: supply grills" },
    { id: 169, name: "Mechanical: swamp coolers" },
    { id: 170, name: "Mechanical: thermostat" },
    { id: 171, name: "Mechanical: vent covers (floor)" },
    { id: 172, name: "Metals: bollards" },
    { id: 173, name: "Metals: cable rail" },
    { id: 174, name: "Metals: guardrail" },
    { id: 175, name: "Metals: handrails" },
    { id: 176, name: "Metals: metal fences" },
    { id: 177, name: "Metals: metal gates" },
    { id: 178, name: "Metals: roof deck" },
    { id: 179, name: "Metals: roof trusses" },
    { id: 180, name: "Metals: structural steel" },
    { id: 181, name: "Millwork - interior: balastrade" },
    { id: 182, name: "Millwork - interior: baseboard" },
    { id: 183, name: "Millwork - interior: crown moulding" },
    { id: 184, name: "Millwork - interior: door trim" },
    { id: 185, name: "Millwork - interior: handrails" },
    { id: 186, name: "Millwork - interior: mantel" },
    { id: 187, name: "Millwork - interior: shelf and pole" },
    { id: 188, name: "Millwork - interior: shelving" },
    { id: 189, name: "Millwork - interior: window trim" },
    { id: 190, name: "Millwork - interior: wood paneling" },
    { id: 191, name: "Millwork - interior: wood shelves" },
    { id: 192, name: "Millwork - exterior: arbor" },
    { id: 193, name: "Millwork - exterior: channel siding" },
    { id: 194, name: "Millwork - exterior: decking" },
    { id: 195, name: "Millwork - exterior: gazebo" },
    { id: 196, name: "Millwork - exterior: lap siding" },
    { id: 197, name: "Millwork - exterior: shingle siding" },
    { id: 198, name: "Millwork - exterior: trellis" },
    { id: 199, name: "Millwork - exterior: wood soffit" },
    { id: 200, name: "Office equipment: computer keyboards" },
    { id: 201, name: "Office equipment: computer screens" },
    { id: 202, name: "Office equipment: computers" },
    { id: 203, name: "Office equipment: copiers" },
    { id: 204, name: "Office equipment: printers" },
    { id: 205, name: "Painting and wallcovering:" },
    { id: 206, name: "Plumbing: backflow preventer" },
    { id: 207, name: "Plumbing: bathtub" },
    { id: 208, name: "Plumbing: boiler" },
    { id: 209, name: "Plumbing: drinking fountains - porcelain" },
    { id: 210, name: "Plumbing: drinking fountains - stainless" },
    { id: 211, name: "Plumbing: faucets" },
    { id: 212, name: "Plumbing: pressure reducer valve" },
    { id: 213, name: "Plumbing: shower head" },
    { id: 214, name: "Plumbing: sinks - pedestal" },
    { id: 215, name: "Plumbing: sinks - porcelain" },
    { id: 216, name: "Plumbing: sinks - stainless steel" },
    { id: 217, name: "Plumbing: toilets - floor mount" },
    { id: 218, name: "Plumbing: toilets - wall mount" },
    { id: 219, name: "Plumbing: tub spout" },
    { id: 220, name: "Plumbing: urinal" },
    { id: 221, name: "Plumbing: water heater - tank" },
    { id: 222, name: "Plumbing: water heater - tankless" },
    { id: 223, name: "Roofing: composition" },
    { id: 224, name: "Roofing: epdm" },
    { id: 225, name: "Roofing: metal" },
    { id: 226, name: "Roofing: tpo" },
    { id: 227, name: "Roofing: wood shingle or shakes" },
    { id: 228, name: "Sheetmetal: sheetmetal misc" },
    { id: 229, name: "Sheetmetal: soffit vent" },
    { id: 230, name: "Site: decks" },
    { id: 231, name: "Site: fencing -  wood" },
    { id: 232, name: "Site: fencing - metal" },
    { id: 233, name: "Site: sheds" },
    { id: 234, name: "Soil:" },
    { id: 235, name: "Specialties: acoustical wall panels" },
    { id: 236, name: "Specialties: baby changing table" },
    { id: 237, name: "Specialties: bike racks" },
    { id: 238, name: "Specialties: chalk boards" },
    { id: 239, name: "Specialties: cork boards" },
    { id: 240, name: "Specialties: cup dispensers" },
    { id: 241, name: "Specialties: fire extinguisher" },
    { id: 242, name: "Specialties: fireplace" },
    { id: 243, name: "Specialties: flower boxes - metal" },
    { id: 244, name: "Specialties: flower boxes - wood" },
    { id: 245, name: "Specialties: hooks - storage" },
    { id: 246, name: "Specialties: mail slot" },
    { id: 247, name: "Specialties: mailboxes" },
    { id: 248, name: "Specialties: overhead storage racks" },
    { id: 249, name: "Specialties: pegboard" },
    { id: 250, name: "Specialties: pin up boards" },
    { id: 251, name: "Specialties: portable clothes hangers" },
    { id: 252, name: "Specialties: portable heaters" },
    { id: 253, name: "Specialties: pull down ladder" },
    { id: 254, name: "Specialties: shelves with brackets" },
    { id: 255, name: "Specialties: signage" },
    { id: 256, name: "Specialties: signage - ada" },
    { id: 257, name: "Specialties: ski racks" },
    { id: 258, name: "Specialties: toilet partitions" },
    { id: 259, name: "Specialties: walk off matts" },
    { id: 260, name: "Specialties: white boards" },
    { id: 261, name: "Specialties: wire shelving" },
    { id: 262, name: "Specialties: wood pallets" },
    { id: 263, name: "Sports equipment: basketball hoop" },
    { id: 264, name: "Sports equipment: bikes" },
    { id: 265, name: "Sports equipment: ping pong table" },
    { id: 266, name: "Sports equipment: pool table" },
    { id: 267, name: "Sports equipment: weights" },
    { id: 268, name: "Stucco/Plaster: plaster" },
    { id: 269, name: "Stucco/Plaster: stucco" },
    { id: 270, name: "Tile: Tile" },
    { id: 271, name: "Underground infrastructure: electrical conduits and wire" },
    { id: 272, name: "Underground infrastructure: gas pipe" },
    { id: 273, name: "Underground infrastructure: perforated pipe" },
    { id: 274, name: "Underground infrastructure: sewer pipe" },
    { id: 275, name: "Underground infrastructure: storm drain pipe" },
    { id: 276, name: "Underground infrastructure: water pipe - domestic" },
    {
        id: 277,
        name: "Underground infrastructure: water pipe - fire suppression",
    },
    { id: 278, name: "Underground infrastructure: water wells" },
    { id: 279, name: "Windows: aluminum" },
    { id: 280, name: "Windows: steel" },
    { id: 281, name: "Windows: vinyl" },
    { id: 282, name: "Windows: wood" },
];
var SearchHandler = /** @class */ (function () {
    function SearchHandler() {
        this.searchInput = document.getElementById("search-input");
        this.resultsList = document.getElementById("results-list");
        this.initializeEventListeners();
    }
    SearchHandler.prototype.initializeEventListeners = function () {
        this.searchInput.addEventListener("input", this.handleSearch.bind(this));
    };
    SearchHandler.prototype.handleKeyDown = function (event) {
        if (event.key === "Escape") {
            this.searchInput.value = "";
            this.displayResults([]);
        }
    };
    SearchHandler.prototype.handleSearch = function () {
        var searchTerm = this.searchInput.value.toLowerCase();
        var filteredItems = items.filter(function (item) {
            return item.name.toLowerCase().includes(searchTerm);
        });
        this.displayResults(filteredItems);
    };
    SearchHandler.prototype.displayResults = function (results) {
        var _this = this;
        this.resultsList.innerHTML = "";
        results.forEach(function (item) {
            var li = document.createElement("li");
            li.innerHTML = "<span style=\"font-size: 2em;\">".concat(item.id, " -   ").concat(item.name, "</span>");
            li.style.listStyleType = "none";
            _this.resultsList.appendChild(li);
        });
    };
    return SearchHandler;
}());
// Initialize the search handler when the DOM is ready
document.addEventListener("DOMContentLoaded", function () {
    new SearchHandler();
});
